apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceprod-buildbot-worker-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 10Gi